### ISSUE TITLE
model.py 的 GCN_emb 类

### ISSUE THREAD

**Issue by SwaggyZhang** [SongW-SW/X-FNC#1]
作者您好，我在学习您代码时，注意到model.py 的line 114，line 115两行
```python
        self.gc1 = GraphConvolution(nfeat, nhid)
        self.gc2 = GraphConvolution(nhid, nhid)
```
中`GraphConvolution()`被ide识别为未定义的函数，请问此处是否为笔误呢？

**Comment by SongW-SW** [comment]
Thanks for pointing this out. I have updated the code and included the class definition.
